apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "ai-demo-app"
  description: "OpenShift Commons keynote SRE Agent demo application"
  annotations:
    argocd/app-selector: tssc/gitops=ai-demo-app
    backstage.io/kubernetes-id: ai-demo-app
    janus-idp.io/tekton: ai-demo-app
    backstage.io/source-location: url:https://github.com/pipelines-as-code/ai-demo-app/tree/main
    backstage.io/techdocs-ref: url:https://github.com/pipelines-as-code/ai-demo-app
    quay.io/repository-slug: "tssc/ai-demo-app"
  tags:
    - java
    - quarkus
  links:
    - url: https://devspaces.apps.cluster-smnvd.dyn.redhatworkshops.io/#https://github.com/pipelines-as-code/ai-demo-app
      title: Open in OpenShift Dev Spaces
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/user1"
  providesApis:
    - "ai-demo-app"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "ai-demo-app"
  description: "OpenShift Commons keynote SRE Agent demo application API"
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/user1"
  definition:
    $text: ./openapi.yaml
