apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: promote-to-prod
  annotations:
    pipelinesascode.tekton.dev/on-event: "[release]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/pipeline: "tkn/pipelines/promote-to-env.yaml"
    pipelinesascode.tekton.dev/task: "[tkn/tasks/gather-images-to-verify.yaml, tkn/tasks/verify-enterprise-contract.yaml, tkn/tasks/skopeo-copy.yaml, tkn/tasks/update-deployment.yaml]"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
  labels:
    backstage.io/kubernetes-id: "ai-demo-app"
spec:
  params:
    - name: git-url
      value: "{{repo_url}}"
    - name: revision
      value: "{{body.ref}}"
    - name: target-branch
      value: "prod-{{body.ref}}"
    - name: source-image
      value: "quay-smnvd-1.apps.cluster-smnvd.dyn.redhatworkshops.io/tssc/ai-demo-app"
    - name: source-image-tag
      value: "{{body.ref}}"
    - name: environment
      value: prod
  pipelineRef:
    name: promote-to-env
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: gitops-auth
      secret:
        secretName: "{{ git_auth_secret }}"
