apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: promote-to-prod
  annotations:
    # The event we are targeting as seen from the webhook payload
    # this can be an array too, i.e: [pull_request, push]
    pipelinesascode.tekton.dev/on-event: "[release]"

    # The branch or tag we are targeting (ie: main, refs/tags/*)
    pipelinesascode.tekton.dev/on-target-branch: "[main]"

    pipelinesascode.tekton.dev/pipeline: "https://raw.githubusercontent.com/blues-man/my-quarkus-tkn/refs/heads/master/tkn/pipelines/promote-to-env.yaml"
    pipelinesascode.tekton.dev/task-1: "https://raw.githubusercontent.com/blues-man/my-quarkus-tkn/refs/heads/master/tkn/tasks/gather-images-to-verify.yaml"
    pipelinesascode.tekton.dev/task-2: "https://raw.githubusercontent.com/blues-man/my-quarkus-tkn/refs/heads/master/tkn/tasks/verify-enterprise-contract.yaml"
    pipelinesascode.tekton.dev/task-3: "https://raw.githubusercontent.com/blues-man/my-quarkus-tkn/refs/heads/master/tkn/tasks/skopeo-copy.yaml"
    pipelinesascode.tekton.dev/task-4: "https://raw.githubusercontent.com/blues-man/my-quarkus-tkn/refs/heads/master/tkn/tasks/update-deployment.yaml"
  labels:
    backstage.io/kubernetes-id: "my-quarkus-tkn"
spec:
  params:
  - name: git-url
    value: '{{repo_url}}'
  - name: revision
    value: '{{body.ref}}'
  - name: target-branch
    value: 'prod-{{body.ref}}'
  - name: source-image
    value: 'quay-892bb-1.apps.cluster-892bb.dynamic.redhatworkshops.io/tssc/my-quarkus-tkn'
  - name: source-image-tag
    value: '{{body.ref}}'
  - name: environment
    value: prod
  pipelineRef:
    name: promote-to-env
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: gitops-auth
      secret:
        secretName: "{{ git_auth_secret }}"
